name: example-environment
channels:
  - conda-forge
dependencies:
  - os
  - sys
  - argparse
  - glob
  - math
  - importlib
  - itertools
  - time
  - numpy
  - pandas
  - matplotlib
  - scipy
  - tifffile
  - IPython
